name: deploy to production
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: list directories before checkout
        run: ls -la

      - name: Checkout code
        uses: actions/checkout@v2

      - name: List directories after checkout
        run: ls -la  

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'

      # - name: Install dependencies
      #   run: npm install

      # - name: Build the application
      #   run: npm run build

      # - name: Deploy to production
      #   run: npm run deploy